name: Create Plugin ZIP

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      plugin_url: ${{ steps.plugin_url.outputs.plugin_url }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get ZIP structure
        id: zip_structure
        run: |
          FILES=$(jq -r '.entries[]' .to_zip.json | paste -sd " " -)
          ROOT=$(jq -r '.root' .to_zip.json)
          echo "root=$ROOT" >> $GITHUB_OUTPUT
          echo "files=$FILES" >> $GITHUB_OUTPUT

      - name: Create ZIP
        run: | 
          tar -acf plugin.zip \
          --transform "s,^,${{ steps.zip_structure.outputs.root }}/," \
          --exclude='__pycache__' \
          ${{ steps.zip_structure.outputs.files }}

      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v2
        with:
          files: plugin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Return URL
        id: plugin_url
        run: |
          echo "plugin_url=https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/plugin.zip" >> $GITHUB_OUTPUT